// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inference struct {
	OutputPath pgtype.Timestamptz
	ResumeFrom pgtype.Timestamptz
	ImagePath  string
	MaskPath   string
	Prompt     string
	NegPrompt  string
	FinishedAt pgtype.Timestamptz
}

type Rating struct {
	JsonPath  pgtype.Timestamptz
	SampleID  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Sample struct {
	SaveDir    pgtype.Timestamptz
	ResumeFrom pgtype.Timestamptz
	ImageFn    string
	PromptFn   string
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type Train struct {
	LogPath    pgtype.Timestamptz
	RatingID   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}
