// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inference struct {
	ID         string
	ModelID    string
	Prompt     string
	NegPrompt  string
	FinishedAt pgtype.Timestamptz
}

type Model struct {
	ID        string
	Domain    string
	ParentID  pgtype.Text
	Status    string
	SampleID  pgtype.Text
	TrainID   pgtype.Text
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Sample struct {
	ID         string
	ModelID    string
	FinishedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Train struct {
	ID         string
	SampleID   string
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}
