// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	TaskID   string
	Order    int16
	Image    []byte
	ImageUrl pgtype.Text
	Mask     []byte
	MaskUrl  pgtype.Text
}

type BaseAsset struct {
	ID       string
	Image    []byte
	ImageUrl string
	Mask     []byte
	MaskUrl  string
	Domain   string
}

type Inference struct {
	ID        string
	Image     []byte
	ImageUrl  string
	Mask      []byte
	MaskUrl   string
	Output    []byte
	OutputUrl string
	FromModel string
}

type Model struct {
	ID        string
	Domain    string
	Name      string
	Base      string
	Ckpt      []byte
	CreatedAt pgtype.Timestamp
}

type Task struct {
	ID            string
	SourceModelID string
	OutputModelID pgtype.Text
	TaskType      string
	CreatedAt     pgtype.Timestamp
	HandledAt     pgtype.Timestamp
	FinishedAt    pgtype.Timestamp
	HumanPrefs    []byte
	PromptEmbeds  []byte
	Latents       []byte
	Timesteps     []byte
	NextLatents   []byte
	ImageTorchs   []byte
}
