// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSample = `-- name: InsertSample :exec
INSERT INTO samples (
    save_dir, resume_from, image_fn, 
    prompt_fn, created_at, finished_at
) VALUES
(
    $1, $2, $3, $4, now(), NULL
)
`

type InsertSampleParams struct {
	SaveDir    pgtype.Timestamptz
	ResumeFrom pgtype.Timestamptz
	ImageFn    string
	PromptFn   string
}

func (q *Queries) InsertSample(ctx context.Context, arg InsertSampleParams) error {
	_, err := q.db.Exec(ctx, insertSample,
		arg.SaveDir,
		arg.ResumeFrom,
		arg.ImageFn,
		arg.PromptFn,
	)
	return err
}
