// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	CheckModelExists(ctx context.Context, logPath string) (bool, error)
	GetModelByID(ctx context.Context, logPath string) (Train, error)
	GetSampleByModelID(ctx context.Context, saveDir string) (Sample, error)
	InsertInference(ctx context.Context, arg InsertInferenceParams) error
	InsertSample(ctx context.Context, arg InsertSampleParams) error
	InsertTrain(ctx context.Context, arg InsertTrainParams) error
	UpdateFeedBackedSample(ctx context.Context, saveDir string) error
	UpdateSampleFinished(ctx context.Context, saveDir string) error
}

