// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	CheckModelExists(ctx context.Context, id string) (bool, error)
	CheckSampleFinishedByModelID(ctx context.Context, modelID string) (bool, error)
	GetModelByID(ctx context.Context, id string) (Model, error)
	GetSampleByModelID(ctx context.Context, modelID string) (Sample, error)
	InsertInference(ctx context.Context, arg InsertInferenceParams) error
	InsertModel(ctx context.Context, arg InsertModelParams) error
	InsertSample(ctx context.Context, arg InsertSampleParams) error
	InsertTask(ctx context.Context, arg InsertTaskParams) (int32, error)
	InsertTrain(ctx context.Context, arg InsertTrainParams) error
	ListAllUnfinishedInferences(ctx context.Context) ([]ListAllUnfinishedInferencesRow, error)
	ListAllUnfinishedSample(ctx context.Context) ([]Sample, error)
	ListAllUnfinishedTrain(ctx context.Context) ([]ListAllUnfinishedTrainRow, error)
	ListFinishedInferences(ctx context.Context, arg ListFinishedInferencesParams) ([]ListFinishedInferencesRow, error)
	ListModelByDomain(ctx context.Context, domain string) ([]Model, error)
	ListModels(ctx context.Context, dollar_1 []string) ([]Model, error)
	ListTasks(ctx context.Context) ([]Task, error)
	UpdateInferenceFinished(ctx context.Context, id string) error
	UpdateModelStatus(ctx context.Context, arg UpdateModelStatusParams) error
	UpdateSampleFinished(ctx context.Context, id string) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateTrainFinished(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
