base_assets:
  - image_dir: "./data/kvasir/sessile-polyps/images"
    mask_dir: "./data/kvasir/sessile-polyps/masks"
    domain: sessile

  - image_dir: "./data/kvasir/pedunculated-polyps/images/"
    mask_dir: "./data/kvasir/pedunculated-polyps/masks/"
    domain: pedunculated
