version: "3.5"

services:
  postgres:
    container_name: postgres-microservice
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5433:5432"

volumes:
  postgres-db:
    driver: local
