// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.go.sql

package database

import (
	"context"
)

const getModel = `-- name: GetModel :one
SELECT id, domain, name, base, ckpt FROM models
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetModel(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Name,
		&i.Base,
		&i.Ckpt,
	)
	return i, err
}
