# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.26.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Inference:
    output_path: datetime.datetime
    resume_from: Optional[datetime.datetime]
    image_path: str
    mask_path: str
    prompt: str
    neg_prompt: str
    finished_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Rating:
    json_path: datetime.datetime
    sample_id: Optional[datetime.datetime]
    created_at: datetime.datetime


@dataclasses.dataclass()
class Sample:
    save_dir: datetime.datetime
    resume_from: Optional[datetime.datetime]
    image_fn: str
    prompt_fn: str
    created_at: datetime.datetime
    finished_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Train:
    log_path: datetime.datetime
    rating_id: Optional[datetime.datetime]
    created_at: datetime.datetime
    finished_at: Optional[datetime.datetime]
